FROM node:18-alpine

WORKDIR /app

COPY frontend/package*.json ./frontend/

WORKDIR /app/frontend
RUN npm ci

WORKDIR /app
COPY frontend ./frontend

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
